/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <opencv2/core/core.hpp>
#include <opencv2/highgui/highgui.hpp>
#include <opencv2/imgproc/imgproc.hpp>
#include <vector>
#include <algorithm>
#include <cmath>
#include<string.h>
#include <opencv2/opencv.hpp>
#include <iostream>
/* Header for class com_css_myapplication_MainActivity */

#ifndef _Included_com_css_myapplication_MainActivity
#define _Included_com_css_myapplication_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_css_myapplication_MainActivity
 * Method:    convertNativeGray
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_css_myapplication_MainActivity_convertNativeGray
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
